"""initial mission schema

Revision ID: 0b4b281e07e7
Revises: 
Create Date: 2026-06-29 13:52:22.397255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b4b281e07e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processed_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('consumer_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', name='uq_processed_message')
    )
    op.create_table('fires',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('intensity', sa.Integer(), server_default='100', nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('extinguished_at', sa.DateTime(), nullable=True),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fire_mission_id', 'fires', ['mission_id'], unique=False)
    op.create_table('mission_cells',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('terrain', sa.String(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id', 'x', 'y', name='uq_mission_cell')
    )
    op.create_table('mission_control',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id')
    )
    op.create_table('mission_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=True),
    sa.Column('causation_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mission_event_mission_id', 'mission_events', ['mission_id'], unique=False)
    op.create_table('responders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('last_known_x', sa.Integer(), nullable=False),
    sa.Column('last_known_y', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('signal_status', sa.String(), nullable=False),
    sa.Column('path_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('path_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('assigned_fire_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_fire_id'], ['fires.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_responder_mission_id', 'responders', ['mission_id'], unique=False)
    op.create_table('pending_responder_commands',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('responder_id', sa.UUID(), nullable=False),
    sa.Column('command_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['responder_id'], ['responders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pending_responder_commands_responder_id', 'pending_responder_commands', ['responder_id'], unique=False)
    op.create_table('responder_local_outbox',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('responder_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('flushed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['responder_id'], ['responders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_responder_local_outbox_responder_id', 'responder_local_outbox', ['responder_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_responder_local_outbox_responder_id', table_name='responder_local_outbox')
    op.drop_table('responder_local_outbox')
    op.drop_index('ix_pending_responder_commands_responder_id', table_name='pending_responder_commands')
    op.drop_table('pending_responder_commands')
    op.drop_index('ix_responder_mission_id', table_name='responders')
    op.drop_table('responders')
    op.drop_index('ix_mission_event_mission_id', table_name='mission_events')
    op.drop_table('mission_events')
    op.drop_table('mission_control')
    op.drop_table('mission_cells')
    op.drop_index('ix_fire_mission_id', table_name='fires')
    op.drop_table('fires')
    op.drop_table('processed_messages')
    op.drop_table('missions')
    # ### end Alembic commands ###
